### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by eleanorkonik** [akosbalasko/zoottelkeeper-obsidian-plugin#1]
This is non-urgent but I wanted to file it here so I didn't forget: Is there a way to use the "shortest path" option for folders? I'm not using any character for prepending for my indexes, so my root index links perfectly to all of my folder files. It would be awesome if this could also work for my nested folders, like so:

![image](https://user-images.githubusercontent.com/75856959/120890932-d22f0400-c5d3-11eb-8933-eb9203f2c1e8.png)

**Comment by akosbalasko** [comment]
Hi @eleanorkonik ,
I think the nested folders should work now. And the shortest path is unfortunately cannot be implemented, beacause it would mix the links up in the graph view. However I added the filename as preview-text (after the |), which would mean that short links will be displayed in preview mode at least. 
So I would close this request.

**Comment by eleanorkonik** [comment]
Ohhhh that is so nice thank you!
