### ISSUE TITLE
Feature Request: Generate Index Files on Install

### ISSUE THREAD

**Issue by ImranR98** [akosbalasko/zoottelkeeper-obsidian-plugin#10]
Currently, the plugin only generates index files for a particular folder when it detects a change in that folder. This is fine for anyone who has been using the plugin from day one, but not for someone new installing the plugin for use with an existing set of notes.

Ideally, there would be a button that would scan a user's existing folder structure and generate index files wherever they are missing. As it stands, I had to manually create an empty note and drag it into each individual folder to trigger the indexing.

Thanks for your work on this plugin, it makes Obsidian's graph view so much more useful for those with folder based organization 😀

**Comment by akosbalasko** [comment]
Hi @ImranR98 !
Thank you for raising this up, totally makes sense, I'll do it.

**Comment by akosbalasko** [comment]
Released in version 0.16.0
