### ISSUE TITLE
[Feature]: Add different link formats

### ISSUE THREAD

**Issue by bhickta** [akosbalasko/zoottelkeeper-obsidian-plugin#14]
* It sometimes become a visual challenge in edit mode to have long links
* Hence kindly add more options apart from absolute path
  * Shortest path when possible
  * Relative path to file

**Comment by akosbalasko** [comment]
Hi @bhickta , 

Unfortunately, we have to keep the absolute paths in order to make the connections consistent, any other ways may mix the things up and can easily lead to unexpected behavior.
