### ISSUE TITLE
Meta Tags have stopped working after updating from 0.9.0

### ISSUE THREAD

**Issue by jwliles** [akosbalasko/zoottelkeeper-obsidian-plugin#19]
I had the 0.9.0 version of the plugin installed and updated to 0.10.1.
After doing so, the plugin no longer adds the meta tags to the index files, and any existing index file has the meta tags removed when it updates them.

The following is a screen capture of my settings.

![Screenshot_3](https://user-images.githubusercontent.com/13804903/131479353-1873c8fb-8760-4829-ab3c-fec414bfd3fa.png)

If any more information is needed, please let me know.

**Comment by kquinsland** [comment]
I just discovered the plugin... and spent a while trying to figure out what `Meta Tags` are and how they are used / work.  An example in the documentation would be super helpful!

But glad to know the function is broken / i'm not using it wrong.

**Comment by akosbalasko** [comment]
I hope it is fixed, please note that the plugin updates the tags only if there is a "tags" (tagLabel) in the frontmatter.

**Comment by jwliles** [comment]
The tags do update when the index file is updated.

Am I wrong but were the tags automatically added in a previous version of the plugin?

Thanks for the prompt response.

**Comment by akosbalasko** [comment]
@jwliles it looks like that the tagseparator is set to comma, but a space separates the autotags (MOC Zettelkasten). Could you please try the plugin again after settin it consistently?
thank you!

**Comment by jwliles** [comment]
This is the result I get in the Help Vault with default settings.

![default-settings-in-help-vault](https://user-images.githubusercontent.com/13804903/132474787-74f1c87f-78d3-4f46-8ad6-3608de0126db.png)

![default-settings](https://user-images.githubusercontent.com/13804903/132475120-a5393c17-eb5e-41bf-bb45-831f28b9e08f.png)

If I change the tag separator to nothing without manually removing the tags first, I get this.

![change-tag-separator](https://user-images.githubusercontent.com/13804903/132475527-88cf0af4-0cc9-4058-aba6-d8f2d0eebc7d.png)

![no-separator-settings](https://user-images.githubusercontent.com/13804903/132475701-c5765a67-23dd-43f4-8276-956b5f775aff.png)

And if I remove the tags.

![update-meta-tags](https://user-images.githubusercontent.com/13804903/132475930-6e169319-9257-451c-be2e-acb86ccf6e23.png)

If I add a comma after the MOC tag.

![comma-tags](https://user-images.githubusercontent.com/13804903/132476384-4dfb7371-ef53-4e66-808d-6bf6733ec4ef.png)

![comma-separator-settings](https://user-images.githubusercontent.com/13804903/132476502-8a514aed-cb97-4345-890b-3f9cba0f8024.png)

This is the version I am using.

![vault-plugin-settings](https://user-images.githubusercontent.com/13804903/132476868-0b0f97d4-215e-426c-bec2-47538f60bd30.png)

**Comment by akosbalasko** [comment]
Thank you @jwliles for the insights, I investigate it.

**Comment by akosbalasko** [comment]
Hi @jwliles , 

I think this latest release (0.10.3) will fix the issues. Please note that the separator you set will be used to split the (optionally more) tags you set, for instance:
If you set a comma to be a separator, and tag1,tag2 to be added as tags in plugin, it will add two tags, [tag1],[tag2]. But if you miss to specify the separator (default is a command + a space ) and the tags has not such matching substring in them (because of the space in this case we don't have), one tag will be generated only: [tag1,tag2].
