### ISSUE TITLE
Index file should create a list 

### ISSUE THREAD

**Issue by pathakraul** [akosbalasko/zoottelkeeper-obsidian-plugin#2]
Hi,

This plugin really helpful in managing the index of notes. 
Currently it list down the links in paragraph style . Instead it will be helpful if it can create a list, unordered probably.

Thanks
Rahul

**Comment by akosbalasko** [comment]
Hi @pathakraul !
I get your point, thank you for raising this up! 
I implement it output format as a configurable option soon.
On a long term solution would be I think some integration with the Template plugin to set index file format as template. What do you think?

**Comment by pathakraul** [comment]
Yeah, template will be great.

**Comment by akosbalasko** [comment]
Hi @pathakraul ,
I implemented the option to have list (or checkboxes) as index items, it is released in version 0.6.0, you can update the plugin in Obsidian if you wish to try it out. 
Thank you!

**Comment by pathakraul** [comment]
Hi @akosbalasko

It works perfectly, thanks.

One thing I wanted to check is that in my workspace the index file also contains the entry of its own link. Is that I am only having because of some reason or this is how it is.

Thanks
