### ISSUE TITLE
Feature to display the post rather than just the link in the Index will be helpful 💡

### ISSUE THREAD

**Issue by mahadevan** [akosbalasko/zoottelkeeper-obsidian-plugin#21]
An option in the plugin section, to append "!" in front of the index link so that we could view the notes in the preview mode.

_example :_
```
%% Zoottelkeeper: Beginning of the autogenerated index file list  %%
![[AREAS 📂/_Index_of_AREAS 📂|_Index_of_AREAS 📂]]
![[JOURNAL 📔/_Index_of_JOURNAL 📔|_Index_of_JOURNAL 📔]]
%% Zoottelkeeper: End of the autogenerated index file list  %%
```

This is helpful in many cases, like the Index of the Index will show all the subsequent indexes.

**Comment by akosbalasko** [comment]
released in version 0.16.0
