### ISSUE TITLE
Destroys frontmatter when changes are made?

### ISSUE THREAD

**Issue by Galacticminingoperation** [akosbalasko/zoottelkeeper-obsidian-plugin#22]
I have some folder notes with aliases in the front matter. Is there any way to stop this plugin from getting rid of the two "---"'s whenever a change is made?

**Comment by akosbalasko** [comment]
Hi @Galacticminingoperation , I implemented a main toggle to disable updating the frontmatter, please update the plugin to 0.10.3 and give it a try. It is this: 
![Screenshot 2021-09-11 at 10 43 03](https://user-images.githubusercontent.com/11886731/132942089-df9871e7-1798-42b3-8c64-4e90897d0db7.png)

**Comment by Galacticminingoperation** [comment]
For some reason this wasn't working back then, but you updated it and it started working. 

With your recent update, however, I have another problem which is that I can no longer set the label as "aliases." It defaults to "tags."

**Comment by akosbalasko** [comment]
hi @Galacticminingoperation , 
let me open a bug issue for this what you reported to investigate it further. 
Sorry for this long long delay. :/
