### ISSUE TITLE
Sorting the index in Ascending Order

### ISSUE THREAD

**Issue by mahadevan** [akosbalasko/zoottelkeeper-obsidian-plugin#25]
Currently, the index is not getting sorted in ascending alphabetical order.

A feature to sort the index in ascending order would be great.

**Comment by claremacrae** [comment]
I do support this, and feel that this should be the default behaviour, as I can't think of any reason why the current random order would be preferred.

The randomness clutters up version-control histories for Obsidian users who track their changes in git.

It's also a bit more visible now, as the indices used in the Obsidian Community Hub are generated using this tool, and in particular the Contributors and Authors list shows the odd order.

https://publish.obsidian.md/hub/00+-+Meta/00.02+-+Contributors+and+Authors/00.02+-+Contributors+and+Authors

![image](https://user-images.githubusercontent.com/4840096/134747139-6ae639e2-fe42-41fb-b34d-6b462349ac37.png)

**Comment by claremacrae** [comment]
This is the relevant code:

https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin/blob/3763231f601727d7b959355070802aab04570db6/utils/updateIndexContent.ts#L12-L13

I don't know TypeScript - but it seems that the `.join(...)` call must either be collating values in a random order, or more likely, the code that generates the `indexContent` argument generates a container in an unstable order.

So maybe the fix should be in the caller instead?

So I speculate the two options are:

**Option 1**

Change [updateIndexContent](https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin/blob/3763231f601727d7b959355070802aab04570db6/utils/updateIndexContent.ts#L12-L13) to sort the values given in `indexContent`

**Option 2**

Change callers of `updateIndexContent` to sort the array passed in

**Comment by akosbalasko** [comment]
released in version 0.16.0

**Comment by claremacrae** [comment]
> released in version 0.16.0

I've tested it out and it's awesome - huge thanks! 🎉
