### ISSUE TITLE
Plugin doesn't always create an index

### ISSUE THREAD

**Issue by adamantski-birder** [akosbalasko/zoottelkeeper-obsidian-plugin#28]
The plugin is so useful! However, I find there are some folders which are not being indexed. Any idea what's going wrong?

Cheers

**Comment by adamantski-birder** [comment]
Okay, got it. I need to create the file first, then it will populate!

**Comment by akosbalasko** [comment]
Hi @adamantski-birder , jepp, you're right. Moreover, there is an other feat.request to trigger the generation of index files right during the configuration of the plugin.
