### ISSUE TITLE
Meta Tags Issue

### ISSUE THREAD

**Issue by brimwats** [akosbalasko/zoottelkeeper-obsidian-plugin#37]
This issue predated the most recent release, but there needs to be a space following the colon in the meta tags

![image](https://user-images.githubusercontent.com/49103046/134808795-5a96bf37-38ce-4ebc-8f0f-6b544f979699.png)

(you can see where i tried to correct it by adding a space in the settings but that just resulted in `tags:[ MOC]` instead of `tags: [MOC]`

**Comment by brimwats** [comment]
Zoottel also generates invalid YAML by adding another [] field if tags already exist

![image](https://user-images.githubusercontent.com/49103046/134808941-73a39581-2b8b-43d2-8e1f-dc3bd5a13344.png)


Correct would be:

![image](https://user-images.githubusercontent.com/49103046/134808957-86d99eaf-b4f8-4f0d-966e-4efe34ce0663.png)

**Comment by akosbalasko** [comment]
Hi @brimwats ,
I'm sorry, I don't get the point, what is set to your tags field?

**Comment by brimwats** [comment]
here are my settings

![image](https://user-images.githubusercontent.com/49103046/134820913-0e9ca0ba-f778-4672-9d1f-1155116e6c63.png)


When I make a new folder note, it looks like this
![image](https://user-images.githubusercontent.com/49103046/134820963-b35b392f-c8f7-4843-ab7c-a9294ec2d502.png)

then zootel replaces things and adds its own metadata

![image](https://user-images.githubusercontent.com/49103046/134820948-b9fb4066-cc2b-4f66-90bc-08d99d60082e.png)


first off, it creates a line break that isn't needed:
![image](https://user-images.githubusercontent.com/49103046/134821004-9dbfed2e-8764-499e-8c68-0fb76ee10021.png)


then look at the `tags:` field

![image](https://user-images.githubusercontent.com/49103046/134821021-ab4884f5-faa3-4d9c-b5d4-06a760d3c859.png)


that is invalid yaml and the tags do not work


![image](https://user-images.githubusercontent.com/49103046/134821029-1c4dd6e7-3949-4977-a7f2-a3db2b599ccf.png)


valid YAML needs a space after the colon:
![image](https://user-images.githubusercontent.com/49103046/134821045-52922f6f-4b6f-4d05-9f1a-0fd12e70b496.png)



For the second issue, I changed my settings:

![image](https://user-images.githubusercontent.com/49103046/134821075-b1de694f-a3df-4fd4-a290-bc9e6f3ffdcc.png)


Then I hit the "genereate Index now button"

this creates a **second** field with [🗂] in it. that is invalid YAML

![image](https://user-images.githubusercontent.com/49103046/134821102-fa2a0491-248f-40ba-9e59-10112f5edb7c.png)

correct is:

![image](https://user-images.githubusercontent.com/49103046/134821115-045a49d7-9cf3-4792-9893-d154d95b94ac.png)

**Comment by akosbalasko** [comment]
Hi @brimwats ,

thanks a lot, now I get it. I'm on it.

**Comment by akosbalasko** [comment]
Hi @brimwats ,
I released a new version 0.16.2, it should resolve the problem.

**Comment by brimwats** [comment]
thanks so much!
