### ISSUE TITLE
Exclude directory and the self index file from indexing

### ISSUE THREAD

**Issue by pathakraul** [akosbalasko/zoottelkeeper-obsidian-plugin#4]
Hi @akosbalasko 

Currently the index file also index the directory in which it is present and also it indexes itself. 
Both I think are not necessary. 

Ideally an index file should list down only two things -
1. Index files of the sub-directories 
2. Files present in the same directory

Please let me know that you think on this

Thanks
Rahul

**Comment by akosbalasko** [comment]
HI @pathakraul !
Sorry for this late reaction, I totally missed your issue.
I was focusing on the chains shown by the Graph View during the implementation, and the connection between the real folders was working by adding the folders into the index files. But let me play a bit more with it to see whether there is an option to achieve everything together. 

Excluding the index file itself is a cool request, I was just lazy by not filtering that out. I'll do that soon. 

Thank you for raising these up!
