### ISSUE TITLE
[Freature]: Do not delete content that is added via Templates or other Pluging (Like Folder Notes)

### ISSUE THREAD

**Issue by blaettlerio** [akosbalasko/zoottelkeeper-obsidian-plugin#43]
Hi,

When a Folder Note is created via Folder Notes (I am using AidenLx's Folder Notes) the content is being overwritten by Zootelkepper.

Would be nice if there would be the possibility that Zootttelkeeper only appends the index content and not overwrite it.

Regards,
Alain

**Comment by akosbalasko** [comment]
Hi @blaettlerio ,

The plugin should update the content between the two placeholders (start with %% in the index file), and should keep the other part untouched. (except the frontmatter if you prefer)
