### ISSUE TITLE
Deleting a folder in Obsidian does not regenerate the index in the parent directory

### ISSUE THREAD

**Issue by claremacrae** [akosbalasko/zoottelkeeper-obsidian-plugin#44]
I'm trying to workaround all the dangling links from cases I described in #41...

## More realistic repro

Given this:

Parent Folder/Child Folder/[various .html files]

I was getting a dangling link in Parent Folder's index, saying Child Folder didn't have an Index.

I decided I didn't care about the old html files, so in Obsidian's navigator, I right0clicked on the 'Child Folder' and deleted it.

The index in Parent Folder was not regenerated.

## Original Report

I had this, where _scripts was an empty folder:

![image](https://user-images.githubusercontent.com/4840096/136687506-a5ec13bf-f3fb-486b-8fea-b97e4670f75e.png)

So there was no index in _scripts.

Outside of Obsidian, I deleted the _scripts folder.

I expected that this plugin would regenerate the index and fix the link.

It didn't, and I had to trigger regelation manually.

Is this expected?

**Comment by akosbalasko** [comment]
Hi @claremacrae ,
Yes, it is expected, if you delete a folder outside of Obsidian, there is no trigger that should push the reindexing. And because of performance considerations the reindexing is done on a folder (and it's parent) where an action (file creation/rename/deletion) was taken.
