### ISSUE TITLE
Inconsistent Ordering of Files in the Index

### ISSUE THREAD

**Issue by ImranR98** [akosbalasko/zoottelkeeper-obsidian-plugin#45]
Zoottelkeeper orders files in the index in a way that is not consistent with Obsidian's own ordering, specifically when it comes to numbers.

This is how files are ordered in Obsidian's navigation tab:
![image](https://user-images.githubusercontent.com/30463115/138135621-ddb147f3-b030-4c07-9252-d082faa10fb4.png)

But this is how the same folder is shown in Zoottelkeeper's index:
![image](https://user-images.githubusercontent.com/30463115/138135665-5052b494-7586-4779-ab25-4c9a03e3b891.png)

Obsidian recognizes that 9 < 10, but Zoottelkeeper thinks 10 should be right after 1 as that is technically right if you're just thinking about alphabetical ordering.

Is this intended behaviour? I think it would make more sense to go with Obsidian's default approach.

**Comment by seanjun21** [comment]
I noticed very similar behavior when using dataview (plugin) to sort metadata.
- For instance, if I have a dataset that's 1, 200, 15, 3, it will basically sort in 1-15-200-3 order.

I had to make sure to convert fields into numbers using the number() function.
I'm sure within this plugin, we can do something similar.

**Comment by akosbalasko** [comment]
HI @seanjun21 , @ImranR98 ,
Thanks for reporting this issue, the order you get is called lexicographical which results a bit different order in case of numbers. But I see it is a problem, so I fix it soon.
