### ISSUE TITLE
Help with included and excluded folders

### ISSUE THREAD

**Issue by PabloOQ** [akosbalasko/zoottelkeeper-obsidian-plugin#48]
Hello, I think I'm not understanding correctly how the exluded and included folders work, I have tried a lot of combinations but I can't make it work.
My case is the following, let's say I have a vault `Vault`, a folder `A` and a folder `B`. I want to dynamically have Zoottelkeeper make an index for folder `A` and all it's subfolders, dynamically. For folder `B` I want the opposite, I do not want Zoottelkeeper to make any indexes to folder `B` and all it's subfolders, dynamically. Worst case scenario I create a Vault for each of these folder, but I rather keep them in the same vault so I can link the notes of these together when needed. Also if I can avoid having an index in the root of the Vault that would be great, but I don't mind it if it can't be removed.
Related to #42 .
Thank you.

**Comment by 23727** [comment]
> Hello, I think I'm not understanding correctly how the exluded and included folders work, I have tried a lot of combinations but I can't make it work.
> 
> My case is the following, let's say I have a vault `Vault`, a folder `A` and a folder `B`. I want to dynamically have Zoottelkeeper make an index for folder `A` and all it's subfolders, dynamically. For folder `B` I want the opposite, I do not want Zoottelkeeper to make any indexes to folder `B` and all it's subfolders, dynamically. Worst case scenario I create a Vault for each of these folder, but I rather keep them in the same vault so I can link the notes of these together when needed. Also if I can avoid having an index in the root of the Vault that would be great, but I don't mind it if it can't be removed.
> 
> Related to #42 .
> 
> Thank you.

Did you ever find a solution to this issue?

**Comment by PabloOQ** [comment]
No, I don't think is possible to do this automatically yet

**Comment by 23727** [comment]
> 

I see. Are you still using the plug-in or are you creating your indexes/MOCs manually?

**Comment by 23727** [comment]
thank you, @PabloOQ

**Comment by akosbalasko** [comment]
Hi all,

in version 0.18.0 I tried to improve the include/exclude feature, now it accepts absolute folders with or without starting '/' characters, moreover if you type '*' at the end of the folder, it means that the folder and its recursive subfolders are excluded/included. 
Sorry for the problems, I hope it works a bit better now.
