### ISSUE TITLE
ER: section marker change from `---` to `***`

### ISSUE THREAD

**Issue by emory** [akosbalasko/zoottelkeeper-obsidian-plugin#51]
hi, this is an _Enhancement Request_:

I have been using Markdown for deliverables, weblog posts for jekyll, wiki documents etc for quite a while so I'm pretty dilligent about having useful and correct yaml frontmatter in my markdown files. This means I almost always have frontmatter roped off with three hyphens `---` to start and another three to end signaling the rest is document content.

So when I insert a horizontal rule for some reason like just a page break or section change, I use `***` which software I use regularly (Ulysses, DEVONthink, MailMate, whatever markdown extension I have in vscode/vim) renders and treats like a section break/horizontal rule. 

Some software gets confused when (even Obsidian) rendering a document and has done some strange things when encountered in some situations, like if a line is followed by another `---` it might treat the proceeding line as a HEADING. possibly a wiki colloquialism or something, but regardless when I use `***` for HR's it's consistent and doesn't do anything unintended and I would like zootelkeeper to maybe have an option to assign/toggle. 

Personally I think the default should be `***` but changing that is probably going to make a lot of people annoyed so I would be glad to just have a way to specify how I prefer to do things.

**Comment by akosbalasko** [comment]
Hi @emory !

I think it can be achieved by #17 , so, via templates. That is planned to be implemented definitely, I'll keep you posted.
