### ISSUE TITLE
v0.17.2 erases all note content outside of autogenerated index file list

### ISSUE THREAD

**Issue by zhelding** [akosbalasko/zoottelkeeper-obsidian-plugin#54]
The latest version of the plugin (`v0.17.2`) erases all note content outside of the autogenerated index file list.

I am using the default plugin settings -- aside from `indexPrefix` which is set to empty string `""`

**Comment by akosbalasko** [comment]
hi @zhelding ,
Please make sure that the placeholders are exactly the same as follows:
%% Zoottelkeeper: Beginning of the autogenerated index file list %%
%% Zoottelkeeper: End of the autogenerated index file list %%

As far as I remember in the previous versions there was an extra space before %% at the end in each, I removed that, so it may cause the sympthoms.

**Comment by akosbalasko** [comment]
Hi @zhelding ,
I'm sorry for the inconveniences, I set the typo back to keep backward compatibility. 
Thank you for raising this up, now it should work with custom index files.

**Comment by zhelding** [comment]
I can confirm that my note content is being preserved upon upgrading from `v0.16.2` to new latest version `v0.17.3`.

Thanks for the quick fix 🚀
