### ISSUE TITLE
Feature Request: Make Compatible with Folder Note Plugin

### ISSUE THREAD

**Issue by brimwats** [akosbalasko/zoottelkeeper-obsidian-plugin#6]
Ideally, I would just like to have an index file that is the same name as the folder, like so

![image](https://user-images.githubusercontent.com/49103046/127118991-3cf2a857-fa5b-48d3-9510-151aeaf8d260.png)

However I'd like to also use folder note to serve as a README for each folder.

When I try to do that like so:

![image](https://user-images.githubusercontent.com/49103046/127119148-433dd23f-280b-49c1-bac2-36cf320f52d8.png)

The index entry for the file name is removed, the folder note section persists for a moment but then is deleted: 
![asQl2CKkMc](https://user-images.githubusercontent.com/49103046/127120844-da062007-26d0-4862-b828-e96c2332f847.gif)

**Comment by MichaBrugger** [comment]
@brimwats, do I understand you correctly (sorry, there is a lot going on in your screenshots 😅). You would like two separate files one is the index-file and one is the folder-note README? And the README file is being removed even though you have a prefix in front of the index-file (so they are not named the same way)?

I'm asking because I'm using the combination of Zoottelkeeper and Folder Note myself and didn't face this issue so far, neither with OG Zoottelkeeper nor with my fork.

**Comment by brimwats** [comment]
I would like one file for both! Folder Note is not deleting from the index file just Zootlekeeper. I would like Zootlekeeper to just append to or remove from the index file below the folder note. 

perhaps this could be indicated with a --- or something to tell Zootel "hey only append and remove below this line" if you needed that programmatically?

**Comment by brimwats** [comment]
Ideally I'd like to remove the prefix from the Zootlekeeper note all together and have it be named the same as the folder.

an additional request might be to allow folder note to rename the folder and have Zootel understand that (if possible), but I understand that would be harder and involve more

**Comment by MichaBrugger** [comment]
Ah, now I understand! I might have some time this weekend so I'll see if I can implement those suggestions in my fork (since I don't have access to Zoottelkeeper directly). If I find the time to solve it, I'll make a Pull Request then akosbalasko can decide if he would like to implement the changes as suggested. Anyway, I'll keep you updated 👍🏼

**Comment by akosbalasko** [comment]
@MichaBrugger thanks for your PR, please check my findings. Thanks for your amazing job!

**Comment by ccc-dvansevenant** [comment]
Brilliant! I just came here to ask about the same thing.

I have a folder full of Articles that I've downloaded in markdown format.

I started using Zootelkeeper to create an index file to list them, and then thought of Folder Note and wondered what would happen if both plugins were told to use, for example, _index_ as the file to write to. Could Folder Note effectively create the front matter/header, and then Zootelkeeper add the index list?

Looking forward to seeing how/if this works!

**Comment by ccc-dvansevenant** [comment]
> Brilliant! I just came here to ask about the same thing.
> 
> I have a folder full of Articles that I've downloaded in markdown format.
> 
> I started using Zootelkeeper to create an index file to list them, and then thought of Folder Note and wondered what would happen if both plugins were told to use, for example, _index_ as the file to write to. Could Folder Note effectively create the front matter/header, and then Zootelkeeper add the index list?
> 
> Looking forward to seeing how/if this works!

Huh, as I play with this more, it looks like I can achieve what I was initially looking for with folder note by using adding `style: strip` to the ccard setup

![image](https://user-images.githubusercontent.com/41758088/128558716-d7920e46-e460-4a98-9017-15f18be9862e.png)

![image](https://user-images.githubusercontent.com/41758088/128558748-29b65507-d5fd-442e-9a37-a2b3efcbc9a4.png)

Still, it'll be interesting to see what comes of this request.

BTW: Thanks for creating this plugin!

**Comment by MichaBrugger** [comment]
@brimwats @ccc-dvansevenant

As a quick update in this regard: Today I finally managed to get rid of that one nasty bug I had in my Pull Request. With this, my initial Pull Request will probably go through in the next few days (depends a bit on when akosbalasko got time). It will add some new functionalities to Zoottelkeeper:

Here a screenshot of the new Zoottelkeeper menu for a brief overview:
![image](https://user-images.githubusercontent.com/46029522/128558971-4c1fb8ec-18ff-4ec8-9c0f-0ea46c56c419.png)
(I wrote some more about the new functionalities in my fork, if you're interested you can check it out there)

---

With that out of the way. I'll now be able to focus on the functionalties both of you mentioned. If I'm understanding you correctly, it would be ideal if Zoottelkeeper would just always check if an index-file already has a certain type of content then it would add the index-list afterwards? Would you consider it an option to just shift all the frontmatter creation to Zoottelkeeper (similar to how the new version will now be able to add tags to those files)?

Anyway, let me know what you think! I'll be starting to play around with the various interactions between Zoottelkeeper and Folder Note tonight. And ye, as always, I'll let you know as soon as I know more :)

**Comment by brimwats** [comment]
thanks so so so much for this!!

**Comment by ccc-dvansevenant** [comment]
> @brimwats @ccc-dvansevenant
> 
> With that out of the way. I'll now be able to focus on the functionalties both of you mentioned. If I'm understanding you correctly, it would be ideal if Zoottelkeeper would just always check if an index-file already has a certain type of content then it would add the index-list afterwards? Would you consider it an option to just shift all the frontmatter creation to Zoottelkeeper (similar to how the new version will now be able to add tags to those files)?

I'm not tied to any particular solution, however, if Zoottelkeeper could generate front matter, too, I would be interested in that, and then I could potentially get rid of Folder Notes. But that's just me.

One benefit to Folder Notes is that it will only work on a folder you specify by CTRL+CLICK (and currently I only have one folder I want set up this way), whereas Zoottelkeeper goes through every folder currently. Again, that's just my use-case.

**Comment by brimwats** [comment]
@MichaBrugger (moving from other discussion) — would your changes also be compatible with https://github.com/aidenlx/alx-folder-note/ ?

**Comment by brimwats** [comment]
@akosbalasko — was this merged into new version? Can't tell

**Comment by akosbalasko** [comment]
Hi @brimwats ,
I think yes, it should, in 0.10.1 I improved the code to do not delete the content in the index file, just update the note list within. 
Reflecting on renaming a folder, and hence rename the folder note is done partially, the plugin preserves the old index and generates a new one. 
Frontmatters are supported, so strips mentioned below should work.

However i have to mention that I didn't test Zoottelkeeper with Fordernote, please  test that it fits your needs, and feel free to open issues if you still miss something.
Thank you!

**Comment by brimwats** [comment]
It seems like it's still erasing the folder note. 

Deleting the prefix (so that it reflects the folder name) results in it erasing  the item that looks like this: 
![image](https://user-images.githubusercontent.com/49103046/131223703-4e1c5615-9714-42b7-9e8c-030d3d6d997c.png)

I made a gif:

![gwf1aYboHI](https://user-images.githubusercontent.com/49103046/131223689-53f907ab-44c6-49a3-8e2d-7fa8c007aa5a.gif)

**Comment by akosbalasko** [comment]
Hi @brimwats ,
It can happen if you have a custom index file without the template strings, in this case the whole index file will be erased, as it happened in the previous versions.
If you add the custom stuff after installing the latest plugin and triggered the index file generalization (that will include the template strings as you see in your gif), then it should work properly.

**Comment by brimwats** [comment]
> Hi @brimwats ,
> It can happen if you have a custom index file without the template strings, in this case the whole index file will be erased, as it happened in the previous versions.
> If you add the custom stuff after installing the latest plugin and triggered the index file generalization (that will include the template strings as you see in your gif), then it should work properly.

ahhh I see! I missed that. So, to confirm, i put this in a template:

```
%% Zoottelkeeper: Beginning of the autogenerated index file list  %%

%% Zoottelkeeper: End of the autogenerated index file list  %%
```

**Comment by akosbalasko** [comment]
@brimwats , Confirmed, this is one way, or the other is to let the plugin generate the new format, that will include this proper placeholder, and after then you can customize the index file content.

**Comment by brimwats** [comment]
@akosbalasko it works! can confirm it works with both the original Folder Note and the AidenLX one. One small thing, which I'll make a FR for—because Zootelkeeper is "faster" than other plugins, it ends up making a note before I can manually make a folder note. Do you think there is any way you could add a template feature that is similar to folder note? It wouldn't have to support all of these things, but it would be nice if it could support FOLDER_NAME and FOLDER_PATH like this:

![image](https://user-images.githubusercontent.com/49103046/131256735-2f3cbf23-1cf6-4e90-b70a-f281b43316ef.png)
