### ISSUE TITLE
I cannot get the exclude folder function to work

### ISSUE THREAD

**Issue by UKViking** [akosbalasko/zoottelkeeper-obsidian-plugin#60]
Your documentation says "they must be aboslute paths starting from the root vault seperated with a comma". But, there is no examples- even just a small example would be very helpful!

I have tried the following and nothing exludes the root folder/
/
VaultName/
/VaultName/
/VaultName
/,
VaultName/.
/VaultName/,
/VaultName,
,/,
,VaultName/.
,/VaultName/,
,/VaultName,

What am I doing wrong?

**Comment by UKViking** [comment]
An update - I see it works by doing

FolderName,

HOWEVER, how do I exclude the root folder? I don't want an index there. Nothing works.

**Comment by 23727** [comment]
It would be nice to be able to exclude the root folder

**Comment by jedth** [comment]
Yeah having the same problem :/

**Comment by UKViking** [comment]
To all the users facing this issue, I found a very simple workaround for excluding folders, until the author does an update or responds:

1. Close Obsidian, to prevent it from auto-updating the index files.
2. Open the root index in Text editor. Delete everything inside.
3. Right click, properties (or Get Info on Mac). Make the file read-only.

Voila

**Comment by akosbalasko** [comment]
Hi all,

in version 0.18.0 I tried to improve the include/exclude feature, now it accepts absolute folders with or without starting '/' characters, moreover if you type '*' at the end of the folder, it means that the folder and its recursive subfolders are excluded/included. 
Sorry for the problems, I hope it works a bit better now.
