### ISSUE TITLE
[Bugreport OR Question] Which is the pathstructure to exclude / include folders?

### ISSUE THREAD

**Issue by L00tz1ffer** [akosbalasko/zoottelkeeper-obsidian-plugin#62]
Hey there,
I encountered a little Problem which drives me crazy :D

### Question
>Could you place a comment with an example for everyone, it seems to be quite mysterious how this concept of **comma seperated inclusion / exclusion structures** is working...

### Example 1
i have the folder for example ```/Glossar/```, this is the only folder which should be included in the folders to work on for zoottelkeeper, so how has the string to look like if i want it working?

### Example 2
another example
```/Glossar/```
and 
```/Wichtige%20Dinge/```

### Problem
i tried lots of combinations and its still going throu all my folders and deleting important notes :/

### Special Chars
How do you Handle Special Chars like ``` ``` or ```%20```
```/Glossar/,/Wichtige%20Dinge/``` or ```/Glossar/,/Wichtige Dinge/```

please make some Guide for everyone in your ```readme.md``` this would be quite helpful!!!

>Thank you for your fast Response and your Time for answering this Question. further more i thank you for making this nice little plugin

**Comment by akosbalasko** [comment]
Hi @L00tz1ffer ,

in version 0.18.0 I tried to improve the include/exclude feature, now it accepts absolute folders with or without starting '/' characters, moreover if you type '*' at the end of the folder, it means that the folder and its recursive subfolders are excluded/included. 
Sorry for the problems, I hope it works a bit better now.
