### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by brimwats** [akosbalasko/zoottelkeeper-obsidian-plugin#8]
Received a notification about an update. Tried it and it failed 

I get this:

Failed to load resource: the server responded with a status of 404 ()
github.com/akosbalasko/zoottelkeeper-obsidian-plugin/releases/download/0.7.0/manifest.json:1 Failed to load resource: the server responded with a status of 404 ()
github.com/akosbalasko/zoottelkeeper-obsidian-plugin/releases/download/0.7.0/manifest.json:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by Creling** [comment]
well, @akosbalasko only update the version number in `manifest.json` but not publish a new release. So we cannot update the plugin in OBsidian.

**Comment by akosbalasko** [comment]
Hi @Creling, hi @brimwats !

I know, I increased the version number by mistake, I still would like to test everything together in the master, before let you update the plugin. 
Now I set the version back to 0.6.0 in the manifest, so you should not see that an update is available. 
Thanks for raising this up, the update is coming soon. 

Cheers,
akos
