### ISSUE TITLE
Feature Request: Allow users to select specific directories to index

### ISSUE THREAD

**Issue by ccc-dvansevenant** [akosbalasko/zoottelkeeper-obsidian-plugin#9]
One of the benefits to Zoottelkeeper is that the results are visible in edit mode, as well are preview mode.

If Zoottelkeeper could allow users to select which directories they want to index, that would be great.

For myself, I currently only have one or two directories that I need the index created for.

Yes, I could ignore the other indexes, but my syncing program can't (OneDrive on work PC. Not sure about Google Drive on personal PC). Recently I started working on a new document, and because Zoottelkeeper was doing its job, OneDrive got confused and ended up creating 4 additional copies because it couldn't resolve the sync collisions.

Thanks!

**Comment by akosbalasko** [comment]
Hi @ccc-dvansevenant ! It's a great idea, thank you for raising this up, I'll implement it.

**Comment by akosbalasko** [comment]
I'm thinking on the option to set the subfolders to be included. I think the easiest way would be to provide a free-text in the config in where the root subfolders can be specified separated by comma. Which would mean that ZK will work on every specified folders and their subfolders recursively. If the free text is empty, it would mean that all the vault should be managed.
 What do you think?

**Comment by kquinsland** [comment]
> I'm thinking on the option to set the subfolders to be included. I think the easiest way would be to provide a free-text in the config in where the root subfolders can be specified separated by comma. 

This could work.  Can you tweak this slightly so the list of directories can either be a white or black list?  _most_ of the directories I have _do_ benefit from an index, but a few dont. I know other people that have the exact opposite situation.

**Comment by akosbalasko** [comment]
released in version 0.16.0
